# Generated by Django 5.2.9 on 2026-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkemail",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
