# Generated by Django 5.2.9 on 2026-03-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0002_add_name_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkemail",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("koordinator", "Koordinator"),
                    ("oekonomisk_ansvarlig", "Økonomiansvarlig"),
                    ("begge", "Koordinator + Økonomiansvarlig"),
                    ("foerste_kontakt", "Første kontakt"),
                    ("alle_kontakter", "Alle kontakter"),
                ],
                max_length=30,
            ),
        ),
    ]
