# Generated by Django 5.2.9 on 2026-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0003_expand_recipient_type_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkemailrecipient",
            name="resend_email_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bulkemailrecipient",
            name="resent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Gensendt"),
        ),
        migrations.AddField(
            model_name="bulkemailrecipient",
            name="resent_to",
            field=models.CharField(blank=True, max_length=254, verbose_name="Gensendt til"),
        ),
    ]
