# Generated by Django 5.2.9 on 2026-03-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0004_bulkemailrecipient_resend_email_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkemailrecipient",
            name="bounced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Bouncet"),
        ),
    ]
