# Generated by Django 5.2.9 on 2026-05-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0008_recipient_types_multi"),
        ("courses", "0021_coursesignup_affiliation_xor"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkemailrecipient",
            name="course_signup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="courses.coursesignup",
            ),
        ),
    ]
