# Generated by Django 5.2.10 on 2026-02-04 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_add_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="notify_on_school_signup",
        ),
    ]
