"""Canonical list of the 98 Danish kommuner.

Derived from prod data (2026-04-09) after fixing one known typo
(`Vesthimmerland Kommune` → `Vesthimmerlands Kommune`). Used as the single
source of truth for seeding the `Kommune` table and for validating kommune
dropdowns in forms.
"""

KOMMUNE_NAMES: list[str] = [
    "Aabenraa Kommune",
    "Aalborg Kommune",
    "Aarhus Kommune",
    "Albertslund Kommune",
    "Allerød Kommune",
    "Assens Kommune",
    "Ballerup Kommune",
    "Billund Kommune",
    "Bornholms Regionskommune",
    "Brøndby Kommune",
    "Brønderslev Kommune",
    "Dragør Kommune",
    "Egedal Kommune",
    "Esbjerg Kommune",
    "Faaborg-Midtfyn Kommune",
    "Fanø Kommune",
    "Favrskov Kommune",
    "Faxe Kommune",
    "Fredensborg Kommune",
    "Fredericia Kommune",
    "Frederiksberg Kommune",
    "Frederikshavn Kommune",
    "Frederikssund Kommune",
    "Furesø Kommune",
    "Gentofte Kommune",
    "Gladsaxe Kommune",
    "Glostrup Kommune",
    "Greve Kommune",
    "Gribskov Kommune",
    "Guldborgsund Kommune",
    "Haderslev Kommune",
    "Halsnæs Kommune",
    "Hedensted Kommune",
    "Helsingør Kommune",
    "Herlev Kommune",
    "Herning Kommune",
    "Hillerød Kommune",
    "Hjørring Kommune",
    "Holbæk Kommune",
    "Holstebro Kommune",
    "Horsens Kommune",
    "Hvidovre Kommune",
    "Høje-Taastrup Kommune",
    "Hørsholm Kommune",
    "Ikast-Brande Kommune",
    "Ishøj Kommune",
    "Jammerbugt Kommune",
    "Kalundborg Kommune",
    "Kerteminde Kommune",
    "Kolding Kommune",
    "Københavns Kommune",
    "Køge Kommune",
    "Langeland Kommune",
    "Lejre Kommune",
    "Lemvig Kommune",
    "Lolland Kommune",
    "Lyngby-Taarbæk Kommune",
    "Læsø Kommune",
    "Mariagerfjord Kommune",
    "Middelfart Kommune",
    "Morsø Kommune",
    "Norddjurs Kommune",
    "Nordfyns Kommune",
    "Nyborg Kommune",
    "Næstved Kommune",
    "Odder Kommune",
    "Odense Kommune",
    "Odsherred Kommune",
    "Randers Kommune",
    "Rebild Kommune",
    "Ringkøbing-Skjern Kommune",
    "Ringsted Kommune",
    "Roskilde Kommune",
    "Rudersdal Kommune",
    "Rødovre Kommune",
    "Samsø Kommune",
    "Silkeborg Kommune",
    "Skanderborg Kommune",
    "Skive Kommune",
    "Slagelse Kommune",
    "Solrød Kommune",
    "Sorø Kommune",
    "Stevns Kommune",
    "Struer Kommune",
    "Svendborg Kommune",
    "Syddjurs Kommune",
    "Sønderborg Kommune",
    "Thisted Kommune",
    "Tårnby Kommune",
    "Tønder Kommune",
    "Vallensbæk Kommune",
    "Varde Kommune",
    "Vejen Kommune",
    "Vejle Kommune",
    "Vesthimmerlands Kommune",
    "Viborg Kommune",
    "Vordingborg Kommune",
    "Ærø Kommune",
]

assert len(KOMMUNE_NAMES) == 98, f"Expected 98 kommuner, got {len(KOMMUNE_NAMES)}"
assert len(set(KOMMUNE_NAMES)) == 98, "Duplicate kommune name in KOMMUNE_NAMES"
