# Generated by Django 6.0 on 2025-12-16 12:19

from django.db import migrations, models


def migrate_contacted_at_to_date_time(apps, schema_editor):
    """Migrate contacted_at datetime to separate date and time fields."""
    ContactTime = apps.get_model('contacts', 'ContactTime')
    for contact in ContactTime.objects.all():
        if contact.contacted_at:
            contact.contacted_date = contact.contacted_at.date()
            contact.contacted_time = contact.contacted_at.time()
            contact.save()


def migrate_date_time_to_contacted_at(apps, schema_editor):
    """Reverse migration: combine date and time back to contacted_at."""
    from datetime import datetime
    ContactTime = apps.get_model('contacts', 'ContactTime')
    for contact in ContactTime.objects.all():
        if contact.contacted_date:
            time = contact.contacted_time or datetime.min.time()
            contact.contacted_at = datetime.combine(contact.contacted_date, time)
            contact.save()


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        # Add new fields (nullable initially)
        migrations.AddField(
            model_name='contacttime',
            name='contacted_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contacttime',
            name='contacted_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacttime',
            name='inbound',
            field=models.BooleanField(default=False, verbose_name='Kontaktede de os?'),
        ),
        # Migrate data
        migrations.RunPython(migrate_contacted_at_to_date_time, migrate_date_time_to_contacted_at),
        # Make contacted_date non-nullable
        migrations.AlterField(
            model_name='contacttime',
            name='contacted_date',
            field=models.DateField(),
        ),
        # Remove old field
        migrations.RemoveField(
            model_name='contacttime',
            name='contacted_at',
        ),
        # Update ordering
        migrations.AlterModelOptions(
            name='contacttime',
            options={'ordering': ['-contacted_date', '-contacted_time']},
        ),
    ]
