# Generated by Django 5.2.9 on 2026-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_split_contacted_date_time"),
        ("schools", "0014_remove_school_year_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacttime",
            name="contacted_other",
            field=models.BooleanField(default=False, verbose_name="Anden kontaktperson"),
        ),
        migrations.AddField(
            model_name="contacttime",
            name="contacted_persons",
            field=models.ManyToManyField(
                blank=True,
                related_name="contact_history",
                to="schools.person",
                verbose_name="Kontaktpersoner",
            ),
        ),
    ]
