# Generated by Django 5.2.9 on 2026-01-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "klasseforloeb_per_teacher_per_year",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=4,
                        verbose_name="Klasseforløb pr. lærer pr. år",
                    ),
                ),
                (
                    "students_per_klasseforloeb",
                    models.DecimalField(
                        decimal_places=1,
                        default=24.0,
                        max_digits=5,
                        verbose_name="Elever pr. klasseforløb",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projektindstillinger",
                "verbose_name_plural": "Projektindstillinger",
            },
        ),
    ]
