# Generated by Django 5.2.9 on 2026-03-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_project_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="login_info_text",
            field=models.TextField(
                blank=True,
                help_text="Fritekst med login-oplysninger til sammenomtrivsel.com — vises på alle tilmeldte skolers sider",
                verbose_name="Login-oplysninger",
            ),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="samarbejdsvilkaar_file",
            field=models.FileField(
                blank=True,
                help_text="Fil der vises på alle tilmeldte skolers sider",
                upload_to="site_files/",
                verbose_name="Samarbejdsvilkår (PDF)",
            ),
        ),
    ]
