# Generated by Django 5.2.9 on 2026-03-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_school_page_global_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="show_seat_info_messages",
            field=models.BooleanField(
                default=False,
                help_text="Når slået til, vises informationsbeskeder om pladsstatus på kursustilmeldingssiden",
                verbose_name="Vis pladsinformation ved kursustilmelding",
            ),
        ),
    ]
