# Generated by Django 6.0 on 2025-12-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesignup",
            name="participant_email",
            field=models.EmailField(
                blank=True, help_text="E-mail til kontakt", max_length=254
            ),
        ),
    ]
