# Generated by Django 5.2.9 on 2025-12-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_add_participant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="undervisere",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Undervisere"
            ),
        ),
    ]
