# Generated by Django 5.2.9 on 2025-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_add_participant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="materials",
            field=models.FileField(
                blank=True,
                help_text="PDF med kursusmateriale (sendes med påmindelses-e-mail)",
                upload_to="course_materials/",
                verbose_name="Kursusmateriale",
            ),
        ),
    ]
