# Generated by Django 5.2.9 on 2025-12-17 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_add_undervisere_to_course"),
        ("courses", "0003_initial"),
    ]

    operations = []
