# Generated by Django 5.2.9 on 2026-01-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_merge_0003_add_undervisere_to_course_0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="course_materials/", verbose_name="Fil"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Valgfrit navn til filen",
                        max_length=255,
                        verbose_name="Navn",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_materials",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kursusmateriale",
                "verbose_name_plural": "Kursusmaterialer",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
