# Generated by Django 5.2.9 on 2026-01-13 09:11

from django.db import migrations


def migrate_materials_to_course_material(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    CourseMaterial = apps.get_model('courses', 'CourseMaterial')

    for course in Course.objects.exclude(materials=''):
        if course.materials:
            CourseMaterial.objects.create(
                course=course,
                file=course.materials,
                name=''
            )


def reverse_migration(apps, schema_editor):
    CourseMaterial = apps.get_model('courses', 'CourseMaterial')
    CourseMaterial.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_add_course_material_model"),
    ]

    operations = [
        migrations.RunPython(migrate_materials_to_course_material, reverse_migration),
    ]
