# Generated by Django 5.2.9 on 2026-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_migrate_existing_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesignup",
            name="is_underviser",
            field=models.BooleanField(
                default=True,
                help_text="Afkryds hvis deltageren er underviser (ikke leder/andet)",
                verbose_name="Er underviser",
            ),
        ),
    ]
