# Generated by Django 5.2.9 on 2026-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_add_is_underviser"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesignup",
            name="participant_phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(default=30, verbose_name="Kapacitet"),
        ),
        migrations.AlterField(
            model_name="course",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_date",
            field=models.DateField(verbose_name="Slutdato"),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Offentliggjorte kurser vises på offentlige tilmeldingsformularer",
                verbose_name="Offentliggjort",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Sted"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateField(verbose_name="Startdato"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titel"),
        ),
    ]
