# Generated by Django 5.2.10 on 2026-01-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_add_instructor_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Navn")),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, verbose_name="Adresse"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="Postnummer"),
                ),
                (
                    "municipality",
                    models.CharField(blank=True, max_length=100, verbose_name="By"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lokation",
                "verbose_name_plural": "Lokationer",
                "ordering": ["name"],
            },
        ),
    ]
