# Generated by Django 5.2.9 on 2026-01-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_add_participant_phone"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(fields=("start_date", "end_date"), name="unique_course_dates"),
        ),
    ]
