# Generated by Django 5.2.10 on 2026-01-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_add_location_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="courses.instructor",
                verbose_name="Undervisere",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="location_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.location",
                verbose_name="Lokation",
            ),
        ),
        migrations.AddField(
            model_name="coursesignup",
            name="participant_phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
        ),
    ]
