# Generated by Django 5.2.10 on 2026-01-26 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_migrate_instructors_locations"),
    ]

    operations = [
        # First remove the old CharField 'location'
        migrations.RemoveField(
            model_name="course",
            name="location",
        ),
        # Rename location_new to location
        migrations.RenameField(
            model_name="course",
            old_name="location_new",
            new_name="location",
        ),
        # Remove title
        migrations.RemoveField(
            model_name="course",
            name="title",
        ),
        # Remove undervisere (old CharField)
        migrations.RemoveField(
            model_name="course",
            name="undervisere",
        ),
    ]
