# Generated by Django 5.2.9 on 2026-01-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_remove_old_course_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesignup",
            name="attendance",
            field=models.CharField(
                choices=[
                    ("unmarked", "Tilmeldt"),
                    ("present", "Uddannet"),
                    ("absent", "Fraværende"),
                ],
                default="unmarked",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(fields=("start_date", "end_date"), name="unique_course_dates"),
        ),
    ]
