# Generated by Django 5.2.9 on 2026-01-27 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_add_phone_and_unique_dates"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="unique_course_dates",
        ),
    ]
