# Generated by Django 5.2.9 on 2026-01-27 08:13

from datetime import timedelta

from django.db import migrations, models


def set_default_registration_deadline(apps, schema_editor):
    """Set registration_deadline to 5 weeks before start_date for existing courses."""
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.filter(registration_deadline__isnull=True):
        course.registration_deadline = course.start_date - timedelta(weeks=5)
        course.save(update_fields=["registration_deadline"])


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_remove_unique_course_dates_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="registration_deadline",
            field=models.DateField(
                blank=True,
                help_text="Sidste dato for tilmelding. Som udgangspunkt 5 uger før kursusstart.",
                null=True,
                verbose_name="Tilmeldingsfrist",
            ),
        ),
        migrations.RunPython(set_default_registration_deadline, migrations.RunPython.noop),
    ]
