# Generated by Django 5.2.9 on 2026-01-27 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_add_registration_deadline"),
        ("schools", "0017_add_unique_school_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coursesignup",
            name="unique_signup_per_course",
        ),
        migrations.AddField(
            model_name="coursesignup",
            name="other_organization",
            field=models.CharField(
                blank=True,
                help_text="Udfyldes hvis deltageren ikke er fra en skole (f.eks. kommune, forvaltning)",
                max_length=255,
                verbose_name="Anden organisation",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="registration_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tilmeldingsfrist"
            ),
        ),
        migrations.AlterField(
            model_name="coursesignup",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Skole - kan være tom hvis deltageren er fra en anden organisation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_signups",
                to="schools.school",
            ),
        ),
    ]
