# Generated by Django 5.2.9 on 2026-02-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_add_other_organization_to_signup"),
        ("schools", "0030_remove_seat_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesignup",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signups",
                to="courses.course",
                verbose_name="Kursus",
            ),
        ),
        migrations.AlterField(
            model_name="coursesignup",
            name="participant_email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail til kontakt",
                max_length=254,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="coursesignup",
            name="participant_name",
            field=models.CharField(max_length=255, verbose_name="Navn"),
        ),
        migrations.AlterField(
            model_name="coursesignup",
            name="participant_title",
            field=models.CharField(
                blank=True,
                help_text="Jobtitel eller rolle",
                max_length=255,
                verbose_name="Titel",
            ),
        ),
        migrations.AlterField(
            model_name="coursesignup",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Skole - kan være tom hvis deltageren er fra en anden organisation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_signups",
                to="schools.school",
                verbose_name="Skole",
            ),
        ),
    ]
