# Generated by Django 5.2.9 on 2026-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0017_alter_coursesignup_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesignup",
            name="email_bounced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="E-mail bouncet"),
        ),
    ]
