# Generated by Django 5.2.9 on 2026-04-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_coursesignup_email_bounced_at"),
        ("schools", "0039_seed_all_kommuner"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesignup",
            name="kommune",
            field=models.ForeignKey(
                blank=True,
                help_text="Udfyldes hvis deltageren er ansat i en kommune (ikke på en skole)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_signups",
                to="schools.kommune",
                verbose_name="Kommune",
            ),
        ),
    ]
