# Generated by Django 5.2.9 on 2026-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0020_backfill_coursesignup_kommune"),
        ("schools", "0039_seed_all_kommuner"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coursesignup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("school__isnull", False),
                        ("kommune__isnull", True),
                        ("other_organization", ""),
                    ),
                    models.Q(
                        ("school__isnull", True),
                        ("kommune__isnull", False),
                        ("other_organization", ""),
                    ),
                    models.Q(
                        ("school__isnull", True),
                        ("kommune__isnull", True),
                        models.Q(("other_organization", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="coursesignup_exactly_one_affiliation",
            ),
        ),
    ]
