# Generated by Django 5.2.9 on 2026-01-20 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("schools", "0014_remove_school_year_enrollment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("checkbox", "Afkrydsningsfelt"),
                            ("file", "Filupload"),
                        ],
                        max_length=20,
                        verbose_name="Felttype",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Feltnavn/tekst (HTML tilladt for afkrydsningsfelter)",
                        max_length=500,
                        verbose_name="Label",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(blank=True, max_length=500, verbose_name="Hjælpetekst"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Påkrævet"),
                ),
                (
                    "allowed_extensions",
                    models.CharField(
                        default="pdf,doc,docx,jpg,png",
                        help_text="Kommasepareret liste (kun for filupload)",
                        max_length=100,
                        verbose_name="Tilladte filtyper",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Kun for filupload",
                        verbose_name="Maks. filstørrelse (MB)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Rækkefølge"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Formularfelt",
                "verbose_name_plural": "Formularfelter",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SignupPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("course_signup", "Kursustilmelding"),
                            ("school_signup", "Skoletilmelding"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Sidetype",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Overskrift")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=255, verbose_name="Underoverskrift"),
                ),
                (
                    "intro_text",
                    models.TextField(
                        blank=True,
                        help_text="HTML-tekst der vises over formularen",
                        verbose_name="Introtekst",
                    ),
                ),
                (
                    "success_title",
                    models.CharField(max_length=255, verbose_name="Succesoverskrift"),
                ),
                (
                    "success_message",
                    models.TextField(
                        help_text="HTML-tekst der vises efter vellykket tilmelding",
                        verbose_name="Succesbesked",
                    ),
                ),
                (
                    "submit_button_text",
                    models.CharField(default="Tilmeld", max_length=50, verbose_name="Knaptekst"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deaktiverede sider viser en besked om at tilmelding ikke er mulig",
                        verbose_name="Aktiv",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tilmeldingsside",
                "verbose_name_plural": "Tilmeldingssider",
            },
        ),
        migrations.CreateModel(
            name="SchoolSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_school_name",
                    models.CharField(
                        blank=True,
                        help_text="Hvis skolen ikke er på listen",
                        max_length=255,
                        verbose_name="Nyt skolenavn",
                    ),
                ),
                (
                    "municipality",
                    models.CharField(max_length=100, verbose_name="Kommune"),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=255, verbose_name="Kontaktperson"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="E-mail"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "contact_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Stilling"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Kommentarer")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Behandlet"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Behandlet dato"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_school_signups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Behandlet af",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Eksisterende skole fra listen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_signups",
                        to="schools.school",
                        verbose_name="Skole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skoletilmelding",
                "verbose_name_plural": "Skoletilmeldinger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignupAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(upload_to="signup_attachments/%Y/%m/", verbose_name="Fil"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Originalt filnavn"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Indholdstype",
                    ),
                ),
                (
                    "form_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="signups.signupformfield",
                        verbose_name="Formularfelt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vedhæftet fil",
                "verbose_name_plural": "Vedhæftede filer",
            },
        ),
        migrations.AddField(
            model_name="signupformfield",
            name="signup_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="signups.signuppage",
                verbose_name="Tilmeldingsside",
            ),
        ),
    ]
