# Generated by Django 5.2.9 on 2026-01-20 12:00

from django.db import migrations


def create_default_pages(apps, schema_editor):
    SignupPage = apps.get_model("signups", "SignupPage")

    # Course signup page (migrating text from existing templates)
    SignupPage.objects.create(
        page_type="course_signup",
        title="Tilmelding",
        subtitle="Tilmeld dig et kommende kursus",
        intro_text="",
        success_title="Tilmelding gennemført!",
        success_message="Tak for din tilmelding. Du vil modtage en bekræftelse på e-mail.",
        submit_button_text="Tilmeld",
        is_active=True,
    )

    # School signup page (new page for schools joining Basal)
    SignupPage.objects.create(
        page_type="school_signup",
        title="Tilmeld din skole",
        subtitle="Bliv en del af Basal-projektet",
        intro_text="",
        success_title="Tak for din interesse!",
        success_message="Vi har modtaget din henvendelse og vender tilbage hurtigst muligt.",
        submit_button_text="Send tilmelding",
        is_active=True,
    )


def remove_default_pages(apps, schema_editor):
    SignupPage = apps.get_model("signups", "SignupPage")
    SignupPage.objects.filter(page_type__in=["course_signup", "school_signup"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_pages, remove_default_pages),
    ]
