# Generated by Django 5.2.9 on 2026-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0002_populate_default_pages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signupformfield",
            name="allowed_extensions",
        ),
        migrations.RemoveField(
            model_name="signupformfield",
            name="max_file_size_mb",
        ),
        migrations.AddField(
            model_name="signupformfield",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Dokument som brugeren kan downloade (f.eks. vilkår og betingelser)",
                upload_to="signup_attachments/",
                verbose_name="Vedhæftet fil",
            ),
        ),
        migrations.AlterField(
            model_name="signupformfield",
            name="field_type",
            field=models.CharField(
                choices=[("checkbox", "Afkrydsningsfelt")],
                max_length=20,
                verbose_name="Felttype",
            ),
        ),
        migrations.AlterField(
            model_name="signupformfield",
            name="label",
            field=models.CharField(
                help_text="Feltnavn/tekst (HTML tilladt)",
                max_length=500,
                verbose_name="Label",
            ),
        ),
        migrations.DeleteModel(
            name="SignupAttachment",
        ),
    ]
