# Generated by Django 5.2.9 on 2026-01-23 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0003_simplify_form_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolSignup",
        ),
    ]
