# Generated by Django 5.2.10 on 2026-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0004_remove_schoolsignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatInfoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("first_year_unused", "Første år – ubrugte pladser"),
                            ("first_year_all_used", "Første år – alle pladser brugt"),
                            ("first_year_extra", "Første år – ekstra pladser"),
                            ("forankring_available", "Forankring – plads tilgængelig"),
                            ("forankring_none", "Forankring – ingen gratis pladser"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Scenarie",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Overskrift")),
                (
                    "content",
                    models.TextField(
                        help_text="HTML-tekst der vises i informationsboksen",
                        verbose_name="Indhold",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pladsinformation",
                "verbose_name_plural": "Pladsinformationer",
                "ordering": ["scenario"],
            },
        ),
    ]
