# Generated by Django 5.2.10 on 2026-02-05 10:11

from django.db import migrations

SEAT_INCLUDES_TEXT = """<p><strong>1 kursusplads inkluderer:</strong> 2-dages forløb, overnatning, forplejning, notesbog, faciliteringsguide, 28 elevhæfter og web-app login.</p>"""

PRICE_TABLE = """<p><strong>Priser for ekstra pladser (ekskl. moms):</strong></p>
<ul>
<li>1 ekstra plads: 7.995 kr.</li>
<li>2 ekstra pladser: 15.190 kr.</li>
<li>3 ekstra pladser: 21.586 kr.</li>
</ul>"""

DEFAULTS = [
    {
        "scenario": "first_year_unused",
        "title": "I har ubrugte pladser",
        "content": (
            "<p>Jeres skole har stadig ubrugte kursuspladser fra det første år. "
            "Pladserne udløber ved skoleårets afslutning, så vi anbefaler at I "
            "tilmelder jer snarest.</p>" + SEAT_INCLUDES_TEXT
        ),
    },
    {
        "scenario": "first_year_all_used",
        "title": "Alle pladser er brugt",
        "content": (
            "<p>Jeres skole har brugt alle 3 kursuspladser fra det første år. " "Godt gået!</p>" + SEAT_INCLUDES_TEXT
        ),
    },
    {
        "scenario": "first_year_extra",
        "title": "Køb ekstra pladser",
        "content": (
            "<p>Jeres skole har brugt alle inkluderede kursuspladser. "
            "I kan tilkøbe ekstra pladser til nedenstående priser.</p>" + SEAT_INCLUDES_TEXT + PRICE_TABLE
        ),
    },
    {
        "scenario": "forankring_available",
        "title": "Gratis forankringsplads",
        "content": (
            "<p>Som en del af jeres forankringsaftale har I adgang til "
            "en gratis kursusplads.</p>" + SEAT_INCLUDES_TEXT
        ),
    },
    {
        "scenario": "forankring_none",
        "title": "Ingen gratis pladser",
        "content": (
            "<p>Jeres skole har ingen gratis kursuspladser tilbage i denne periode. "
            "I kan tilkøbe ekstra pladser til nedenstående priser.</p>" + SEAT_INCLUDES_TEXT + PRICE_TABLE
        ),
    },
]


def populate_seat_info_content(apps, schema_editor):
    SeatInfoContent = apps.get_model("signups", "SeatInfoContent")
    for item in DEFAULTS:
        SeatInfoContent.objects.get_or_create(
            scenario=item["scenario"],
            defaults={"title": item["title"], "content": item["content"]},
        )


def reverse_populate(apps, schema_editor):
    SeatInfoContent = apps.get_model("signups", "SeatInfoContent")
    SeatInfoContent.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0005_add_seat_info_content"),
    ]

    operations = [
        migrations.RunPython(populate_seat_info_content, reverse_populate),
    ]
