# Generated by Django 5.2.9 on 2026-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signups", "0008_rename_forankring_to_fortsaetter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signuppage",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("course_signup", "Kursustilmelding"),
                    ("school_signup", "Skoletilmelding"),
                    ("webinar_signup", "Webinartilmelding"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Sidetype",
            ),
        ),
    ]
