# Generated by Django 5.2.9 on 2026-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0021_coursesignup_affiliation_xor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL-slug"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="HTML-tekst der vises på webinarets side",
                        verbose_name="Beskrivelse",
                    ),
                ),
                (
                    "intro_text",
                    models.TextField(
                        blank=True,
                        help_text="HTML-tekst over formularen. Lad være tom for at bruge standardteksten fra Tilmeldingsside-indstillingen.",
                        verbose_name="Introtekst",
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="Starttidspunkt")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=60, verbose_name="Varighed (minutter)"),
                ),
                (
                    "meeting_url",
                    models.URLField(
                        help_text="Zoom/Teams/Meet-link — sendes i bekræftelsesmail, vises ikke offentligt",
                        verbose_name="Mødelink",
                    ),
                ),
                (
                    "access_mode",
                    models.CharField(
                        choices=[
                            ("public", "Offentlig (alle kan tilmelde sig)"),
                            ("school_gated", "Kun tilmeldte skoler"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Adgang",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lad være tom for ubegrænset",
                        null=True,
                        verbose_name="Kapacitet",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Offentliggjorte webinarer er synlige på deres URL",
                        verbose_name="Offentliggjort",
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Tilmeldingsfrist"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="webinars",
                        to="courses.instructor",
                        verbose_name="Undervisere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webinar",
                "verbose_name_plural": "Webinarer",
                "ordering": ["-start_at"],
            },
        ),
    ]
