# Generated by Django 5.2.9 on 2026-05-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0041_do_not_contact_at"),
        ("webinars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarSignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_name",
                    models.CharField(max_length=255, verbose_name="Navn"),
                ),
                (
                    "participant_email",
                    models.EmailField(max_length=254, verbose_name="E-mail"),
                ),
                (
                    "email_bounced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="E-mail bouncet"),
                ),
                (
                    "participant_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "participant_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Titel"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Kun udfyldt for offentlige webinarer hvor deltageren ikke er fra en tilmeldt skole",
                        max_length=255,
                        verbose_name="Organisation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webinar_signups",
                        to="schools.school",
                        verbose_name="Skole",
                    ),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="webinars.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webinartilmelding",
                "verbose_name_plural": "Webinartilmeldinger",
                "ordering": ["webinar", "participant_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("webinar", "participant_email"),
                        name="webinarsignup_unique_email_per_webinar",
                    )
                ],
            },
        ),
    ]
