# Generated by Django 5.2.9 on 2026-05-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webinars", "0002_webinarsignup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinar",
            name="access_mode",
        ),
        migrations.RemoveField(
            model_name="webinar",
            name="registration_deadline",
        ),
        migrations.RemoveField(
            model_name="webinarsignup",
            name="school",
        ),
        migrations.AlterField(
            model_name="webinarsignup",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Hvor deltageren arbejder (valgfrit)",
                max_length=255,
                verbose_name="Organisation",
            ),
        ),
    ]
