# Generated by Django 5.2.9 on 2026-05-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_coursesignup_affiliation_xor"),
        ("webinars", "0003_remove_webinar_access_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinar",
            name="intro_text",
        ),
        migrations.AlterField(
            model_name="webinar",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="HTML-tekst der vises på webinarets side over metadata-kortet",
                verbose_name="Beskrivelse",
            ),
        ),
        migrations.AlterField(
            model_name="webinar",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="webinars",
                to="courses.instructor",
                verbose_name="Oplægsholdere",
            ),
        ),
    ]
