# Generated by Django 5.2.9 on 2026-05-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0041_do_not_contact_at"),
        (
            "webinars",
            "0004_remove_webinar_intro_text_alter_webinar_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinarsignup",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="webinarsignup",
            name="participant_phone",
        ),
        migrations.RemoveField(
            model_name="webinarsignup",
            name="participant_title",
        ),
        migrations.AddField(
            model_name="webinarsignup",
            name="kommune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="webinar_signups",
                to="schools.kommune",
                verbose_name="Kommune",
            ),
        ),
        migrations.AddField(
            model_name="webinarsignup",
            name="school_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Skole"),
        ),
        migrations.AlterField(
            model_name="webinar",
            name="meeting_url",
            field=models.URLField(
                blank=True,
                help_text="Zoom/Teams/Meet-link — sendes til deltagerne i bekræftelsesmailen. Hvis feltet er tomt, oplyses deltageren om at linket eftersendes tættere på datoen.",
                verbose_name="Mødelink",
            ),
        ),
    ]
