# Generated by Django 6.0 on 2025-12-17 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("courses", "0002_add_participant_email"),
        ("schools", "0002_add_seats_management"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Objekt ID")),
                (
                    "object_repr",
                    models.CharField(max_length=255, verbose_name="Objekt beskrivelse"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Oprettet"),
                            ("UPDATE", "Opdateret"),
                            ("DELETE", "Slettet"),
                        ],
                        max_length=10,
                        verbose_name="Handling",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Field changes: {"field": {"old": ..., "new": ...}}',
                        verbose_name="Ændringer",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tidspunkt"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Objekttype",
                    ),
                ),
                (
                    "related_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="courses.course",
                        verbose_name="Relateret kursus",
                    ),
                ),
                (
                    "related_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="schools.school",
                        verbose_name="Relateret skole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktivitetslog",
                "verbose_name_plural": "Aktivitetslogs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_activ_timesta_7c75b8_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_activ_content_84ff00_idx",
                    ),
                    models.Index(
                        fields=["related_school", "-timestamp"],
                        name="audit_activ_related_85e01a_idx",
                    ),
                    models.Index(
                        fields=["related_course", "-timestamp"],
                        name="audit_activ_related_1436a5_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_activ_user_id_9ceb1a_idx",
                    ),
                ],
            },
        ),
    ]
