# Generated by Django 6.0 on 2025-12-16 12:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="enrolled_at",
            field=models.DateField(
                blank=True,
                help_text="Dato for skolens tilmelding til Basal",
                null=True,
                verbose_name="Tilmeldt dato",
            ),
        ),
        migrations.CreateModel(
            name="SeatPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats", models.PositiveIntegerField(verbose_name="Antal pladser")),
                (
                    "purchased_at",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Købsdato"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Noter")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_purchases",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchased_at"],
            },
        ),
    ]
