# Generated by Django 6.0 on 2025-12-17 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_add_seats_management"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Navn")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("koordinator", "Koordinator"),
                            ("skoleleder", "Skoleleder"),
                            ("udskolingsleder", "Udskolingsleder"),
                            ("other", "Andet"),
                        ],
                        default="koordinator",
                        max_length=20,
                        verbose_name="Funktion",
                    ),
                ),
                (
                    "role_other",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Anden funktion"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Kommentar")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primær kontakt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personer",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Kommentar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_comments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_comments",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kommentar",
                "verbose_name_plural": "Kommentarer",
                "ordering": ["-created_at"],
            },
        ),
    ]
