# Generated by Django 6.0 on 2025-12-17 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_migrate_contacts_to_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="school",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="school",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="school",
            name="contact_phone",
        ),
    ]
