# Generated by Django 5.2.9 on 2025-12-17 10:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0006_split_location_to_adresse_kommune"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Navn"),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=50, verbose_name="Fakturanummer"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Beløb"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planlagt"),
                            ("sent", "Sendt"),
                            ("paid", "Betalt"),
                        ],
                        default="planned",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Dato"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Kommentar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faktura",
                "verbose_name_plural": "Fakturaer",
                "ordering": ["-date"],
            },
        ),
    ]
