# Generated by Django 5.2.9 on 2025-12-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0007_add_invoice_model"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["is_active", "name"], name="schools_sch_is_acti_7a7d73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["kommune"], name="schools_sch_kommune_5dce70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["is_active", "kommune"], name="schools_sch_is_acti_f9e33a_idx"
            ),
        ),
    ]
