# Generated by Django 5.2.9 on 2026-01-13 09:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0008_add_school_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='F.eks. "2024-2025"',
                        max_length=20,
                        unique=True,
                        verbose_name="Skoleår",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Typisk 1. august", verbose_name="Startdato"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Typisk 31. juli", verbose_name="Slutdato"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Skoleår",
                "verbose_name_plural": "Skoleår",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SchoolYearEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Dato for tilmelding dette skoleår",
                        verbose_name="Tilmeldingsdato",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="schools.school",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="schools.schoolyear",
                        verbose_name="Skoleår",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skoleårstilmelding",
                "verbose_name_plural": "Skoleårstilmeldinger",
                "ordering": ["-school_year__start_date"],
                "unique_together": {("school", "school_year")},
            },
        ),
    ]
