# Generated by Django 5.2.9 on 2026-01-13 09:04

from datetime import date

from django.db import migrations


def get_school_year_for_date(d):
    """Bestem skoleåret for en given dato. Skoleår går fra 1. aug til 31. juli."""
    if d.month >= 8:
        return d.year, d.year + 1
    else:
        return d.year - 1, d.year


def migrate_enrolled_at_to_enrollments(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    SchoolYear = apps.get_model('schools', 'SchoolYear')
    SchoolYearEnrollment = apps.get_model('schools', 'SchoolYearEnrollment')

    # Opret det nuværende skoleår (2025-2026)
    today = date.today()
    start_year, end_year = get_school_year_for_date(today)
    current_school_year, _ = SchoolYear.objects.get_or_create(
        name=f"{start_year}-{end_year}",
        defaults={
            'start_date': date(start_year, 8, 1),
            'end_date': date(end_year, 7, 31),
        }
    )

    # For hver skole med enrolled_at, opret en tilmelding til nuværende skoleår
    for school in School.objects.filter(enrolled_at__isnull=False):
        SchoolYearEnrollment.objects.get_or_create(
            school=school,
            school_year=current_school_year,
            defaults={
                'enrolled_at': school.enrolled_at,
            }
        )


def reverse_migration(apps, schema_editor):
    # Vi fjerner ikke enrolled_at data, da det stadig bruges til forankringsplads
    SchoolYearEnrollment = apps.get_model('schools', 'SchoolYearEnrollment')
    SchoolYearEnrollment.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0009_add_school_year_models"),
    ]

    operations = [
        migrations.RunPython(migrate_enrolled_at_to_enrollments, reverse_migration),
    ]
