# Generated by Django 5.2.10 on 2026-01-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_migrate_enrolled_at_to_enrollments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['start_date'], 'verbose_name': 'Skoleår', 'verbose_name_plural': 'Skoleår'},
        ),
        migrations.AlterModelOptions(
            name='schoolyearenrollment',
            options={'ordering': ['school_year__start_date'], 'verbose_name': 'Skoleårstilmelding', 'verbose_name_plural': 'Skoleårstilmeldinger'},
        ),
    ]
