# Generated by Django 5.2.9 on 2026-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0011_alter_schoolyear_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="school_years",
            field=models.ManyToManyField(
                blank=True,
                related_name="invoices",
                to="schools.schoolyear",
                verbose_name="Skoleår",
            ),
        ),
    ]
