# Generated by Django 5.2.9 on 2026-01-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0012_add_school_years_to_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="opted_out_at",
            field=models.DateField(
                blank=True,
                help_text="Dato for framelding fra Basal (permanent)",
                null=True,
                verbose_name="Frameldt dato",
            ),
        ),
    ]
