# Generated by Django 5.2.9 on 2026-01-19 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0013_add_opted_out_to_school"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolYearEnrollment",
        ),
    ]
