# Generated by Django 5.2.9 on 2026-01-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0014_remove_school_year_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="signup_password",
            field=models.CharField(
                blank=True,
                help_text="Kode til kursustilmelding",
                max_length=20,
                verbose_name="Tilmeldingskode",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="signup_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Token til direkte link",
                max_length=32,
                verbose_name="Tilmeldingstoken",
            ),
        ),
    ]
