# Generated by Django 5.2.9 on 2026-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0015_add_signup_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="signup_password",
            field=models.CharField(
                blank=True,
                help_text="Kode til kursustilmelding",
                max_length=25,
                verbose_name="Tilmeldingskode",
            ),
        ),
    ]
