# Generated by Django 5.2.9 on 2026-01-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0016_increase_signup_password_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="school",
            constraint=models.UniqueConstraint(fields=("name", "kommune"), name="unique_school_per_kommune"),
        ),
    ]
