# Generated by Django 5.2.9 on 2026-01-27 11:59

import django.db.models.deletion
from django.db import migrations, models


def migrate_m2m_to_fk(apps, schema_editor):
    """Migrate school_years M2M to school_year FK, keeping the first year."""
    Invoice = apps.get_model("schools", "Invoice")
    for invoice in Invoice.objects.all():
        # Get the first school year from the M2M relationship (ordered by start_date desc)
        first_year = invoice.school_years.order_by("-start_date").first()
        if first_year:
            invoice.school_year = first_year
            invoice.save()


def reverse_fk_to_m2m(apps, schema_editor):
    """Reverse migration: copy FK to M2M."""
    Invoice = apps.get_model("schools", "Invoice")
    for invoice in Invoice.objects.all():
        if invoice.school_year:
            invoice.school_years.add(invoice.school_year)


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0018_populate_school_years"),
    ]

    operations = [
        # First, add the new FK field
        migrations.AddField(
            model_name="invoice",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices_new",  # Temporary related_name to avoid conflict
                to="schools.schoolyear",
                verbose_name="Skoleår",
            ),
        ),
        # Migrate data from M2M to FK
        migrations.RunPython(migrate_m2m_to_fk, reverse_fk_to_m2m),
        # Remove the M2M field
        migrations.RemoveField(
            model_name="invoice",
            name="school_years",
        ),
        # Update FK field to use correct related_name
        migrations.AlterField(
            model_name="invoice",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="schools.schoolyear",
                verbose_name="Skoleår",
            ),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="name",
            field=models.CharField(
                help_text='F.eks. "2024/25"',
                max_length=20,
                unique=True,
                verbose_name="Skoleår",
            ),
        ),
    ]
