# Generated by Django 5.2.9 on 2026-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0019_convert_invoice_school_year_to_fk"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("invoice_number", "school_year"),
                name="unique_invoice_per_school_year",
            ),
        ),
    ]
