# Generated by Django 5.2.9 on 2026-01-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0020_add_unique_invoice_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="by",
            field=models.CharField(blank=True, max_length=100, verbose_name="By"),
        ),
        migrations.AddField(
            model_name="school",
            name="ean_nummer",
            field=models.CharField(blank=True, max_length=13, verbose_name="EAN-nummer"),
        ),
        migrations.AddField(
            model_name="school",
            name="postnummer",
            field=models.CharField(blank=True, max_length=4, verbose_name="Postnummer"),
        ),
    ]
