# Generated by Django 5.2.10 on 2026-01-30 12:18

from django.db import migrations, models


def migrate_role_data(apps, schema_editor):
    """
    Migrate existing role data:
    - 'skoleleder' -> 'andet' with role_other='Skoleleder'
    - 'udskolingsleder' -> 'andet' with role_other='Udskolingsleder'
    - 'other' -> 'andet'
    """
    Person = apps.get_model("schools", "Person")

    # Migrate skoleleder to andet
    Person.objects.filter(role="skoleleder").update(role="andet", role_other="Skoleleder")

    # Migrate udskolingsleder to andet
    Person.objects.filter(role="udskolingsleder").update(role="andet", role_other="Udskolingsleder")

    # Migrate other to andet (preserving role_other if set)
    Person.objects.filter(role="other").update(role="andet")


def reverse_role_data(apps, schema_editor):
    """Reverse migration - convert 'andet' back where possible."""
    Person = apps.get_model("schools", "Person")

    # Note: This is a lossy reverse migration since we can't distinguish
    # between original 'other' and migrated 'skoleleder'/'udskolingsleder'
    Person.objects.filter(role="andet", role_other="Skoleleder").update(role="skoleleder", role_other="")
    Person.objects.filter(role="andet", role_other="Udskolingsleder").update(role="udskolingsleder", role_other="")


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0021_add_school_extended_fields"),
    ]

    operations = [
        # Step 1: Add new titel fields
        migrations.AddField(
            model_name="person",
            name="titel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("skoleleder", "Skoleleder"),
                    ("udskolingsleder", "Udskolingsleder"),
                    ("klasselaerer", "Klasselærer"),
                    ("paedagog", "Pædagog"),
                    ("akt_inklusionsvejleder", "AKT/inklusionsvejleder"),
                    ("trivselsvejleder", "Trivselsvejleder"),
                    ("andet", "Andet"),
                ],
                max_length=30,
                verbose_name="Titel",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="titel_other",
            field=models.CharField(blank=True, max_length=100, verbose_name="Anden titel"),
        ),
        # Step 2: Migrate existing role data before changing choices
        migrations.RunPython(migrate_role_data, reverse_role_data),
        # Step 3: Update role field with new choices
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.CharField(
                choices=[
                    ("koordinator", "Koordinator"),
                    ("oekonomisk_ansvarlig", "Økonomisk ansvarlig"),
                    ("andet", "Andet"),
                ],
                default="koordinator",
                max_length=20,
                verbose_name="Funktion",
            ),
        ),
    ]
