# Generated by Django 5.2.9 on 2026-01-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0022_add_titel_to_person_and_update_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="fakturering_adresse",
            field=models.CharField(blank=True, max_length=255, verbose_name="Faktureringsadresse"),
        ),
        migrations.AddField(
            model_name="school",
            name="fakturering_by",
            field=models.CharField(blank=True, max_length=100, verbose_name="By"),
        ),
        migrations.AddField(
            model_name="school",
            name="fakturering_ean_nummer",
            field=models.CharField(blank=True, max_length=13, verbose_name="EAN-nummer"),
        ),
        migrations.AddField(
            model_name="school",
            name="fakturering_kontakt_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
        migrations.AddField(
            model_name="school",
            name="fakturering_kontakt_navn",
            field=models.CharField(blank=True, max_length=255, verbose_name="Kontaktperson"),
        ),
        migrations.AddField(
            model_name="school",
            name="fakturering_postnummer",
            field=models.CharField(blank=True, max_length=4, verbose_name="Postnummer"),
        ),
        migrations.AddField(
            model_name="school",
            name="kommunen_betaler",
            field=models.BooleanField(default=False, verbose_name="Kommunen betaler"),
        ),
    ]
