# Generated by Django 5.2.10 on 2026-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0024_add_school_file_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_koordinator",
            field=models.BooleanField(default=False, verbose_name="Koordinator"),
        ),
        migrations.AddField(
            model_name="person",
            name="is_oekonomisk_ansvarlig",
            field=models.BooleanField(default=False, verbose_name="Økonomisk ansvarlig"),
        ),
    ]
