# Generated by Django 5.2.10 on 2026-02-03 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0026_migrate_person_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["-is_koordinator", "-is_oekonomisk_ansvarlig", "name"],
                "verbose_name": "Person",
                "verbose_name_plural": "Personer",
            },
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="person",
            name="role",
        ),
        migrations.RemoveField(
            model_name="person",
            name="role_other",
        ),
    ]
