# Generated by Django 5.2.10 on 2026-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0027_remove_old_person_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="active_from",
            field=models.DateField(
                blank=True,
                help_text="Dato hvor tilmeldingen træder i kraft (påvirker pladser og forankring)",
                null=True,
                verbose_name="Aktiv fra",
            ),
        ),
    ]
