# Generated by Django 5.2.10 on 2026-02-05 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0029_populate_active_from"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeatPurchase",
        ),
    ]
