# Generated by Django 5.2.9 on 2026-03-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0030_remove_seat_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="active_from",
            field=models.DateField(
                blank=True,
                help_text="Dato hvor tilmeldingen træder i kraft (påvirker pladser og fortsætter-status)",
                null=True,
                verbose_name="Aktiv fra",
            ),
        ),
    ]
