# Generated by Django 5.2.9 on 2026-03-18 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0031_alter_school_active_from"),
        ("schools", "0031_drop_invoice_model"),
    ]

    operations = []
