# Generated by Django 5.2.9 on 2026-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0032_merge_20260318_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email_bounced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="E-mail bouncet"),
        ),
        migrations.AddField(
            model_name="school",
            name="fakturering_email_bounced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fakturerings-e-mail bouncet"),
        ),
    ]
