# Generated by Django 5.2.9 on 2026-04-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0033_person_email_bounced_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="inst_nr",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="STIL-institutionsnummer (bruges som nøgle ved import)",
                max_length=6,
                verbose_name="Institutionsnummer",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="institutionstype",
            field=models.CharField(
                choices=[
                    ("folkeskole", "Folkeskole"),
                    ("friskole", "Fri/privat grundskole"),
                    ("efterskole", "Efterskole"),
                ],
                default="folkeskole",
                max_length=20,
                verbose_name="Institutionstype",
            ),
        ),
    ]
