# Generated by Django 5.2.9 on 2026-04-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0034_school_inst_nr_school_institutionstype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="institutionstype",
            field=models.CharField(
                choices=[
                    ("folkeskole", "Folkeskole"),
                    ("friskole", "Fri/privat grundskole"),
                    ("efterskole", "Efterskole"),
                    ("friskole_efterskole", "Kombineret fri-/efterskole"),
                ],
                default="folkeskole",
                max_length=20,
                verbose_name="Institutionstype",
            ),
        ),
    ]
