# Generated by Django 5.2.9 on 2026-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0035_alter_school_institutionstype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kommune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Kommune"),
                ),
                (
                    "fakturering_adresse",
                    models.CharField(blank=True, max_length=255, verbose_name="Faktureringsadresse"),
                ),
                (
                    "fakturering_postnummer",
                    models.CharField(blank=True, max_length=4, verbose_name="Postnummer"),
                ),
                (
                    "fakturering_by",
                    models.CharField(blank=True, max_length=100, verbose_name="By"),
                ),
                (
                    "fakturering_ean_nummer",
                    models.CharField(blank=True, max_length=13, verbose_name="EAN-nummer"),
                ),
                (
                    "fakturering_kontakt_navn",
                    models.CharField(blank=True, max_length=255, verbose_name="Kontaktperson"),
                ),
                (
                    "fakturering_kontakt_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
                ),
                (
                    "fakturering_email_bounced_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fakturerings-e-mail bouncet",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kommune",
                "verbose_name_plural": "Kommuner",
                "ordering": ["name"],
            },
        ),
    ]
