# Generated by Django 5.2.9 on 2026-04-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0040_school_kommune_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="do_not_contact_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Skolen ønsker ikke at blive kontaktet – undtages fra masseudsendelser",
                null=True,
                verbose_name="Ønsker ikke kontakt",
            ),
        ),
    ]
