# Generated by Django 5.2.9 on 2025-12-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("signup_confirmation", "Tilmeldingsbekræftelse"),
                            ("course_reminder", "Kursuspåmindelse (2 dage før)"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="E-mail type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Kan indeholde variabler som {{ course_title }}",
                        max_length=255,
                        verbose_name="Emne",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        help_text="HTML-indhold. Kan indeholde variabler som {{ participant_name }}",
                        verbose_name="Indhold (HTML)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deaktiver for at stoppe afsendelse af denne e-mail type",
                        verbose_name="Aktiv",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "E-mail skabelon",
                "verbose_name_plural": "E-mail skabeloner",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("signup_confirmation", "Tilmeldingsbekræftelse"),
                            ("course_reminder", "Kursuspåmindelse (2 dage før)"),
                        ],
                        max_length=30,
                        verbose_name="E-mail type",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Modtager"),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=255, verbose_name="Modtager navn"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Emne")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sendt"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Succes")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Fejlbesked"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="courses.course",
                        verbose_name="Kursus",
                    ),
                ),
                (
                    "signup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="courses.coursesignup",
                        verbose_name="Tilmelding",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-mail log",
                "verbose_name_plural": "E-mail logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
