# Generated by Django 5.2.9 on 2025-12-17 10:59

from django.db import migrations


def create_default_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('emails', 'EmailTemplate')

    # Signup confirmation template
    EmailTemplate.objects.get_or_create(
        email_type='signup_confirmation',
        defaults={
            'subject': 'Bekræftelse på tilmelding til {{ course_title }}',
            'body_html': '''<p>Kære {{ participant_name }},</p>

<p>Tak for din tilmelding til kurset <strong>{{ course_title }}</strong>.</p>

<p><strong>Kursusdetaljer:</strong></p>
<ul>
    <li>Dato: {{ course_date }}</li>
    <li>Sted: {{ course_location }}</li>
    <li>Skole: {{ school_name }}</li>
</ul>

<p>Du vil modtage en påmindelse med kursusmateriale 2 dage før kurset.</p>

<p>Med venlig hilsen,<br>
Basal</p>''',
            'is_active': True,
        }
    )

    # Course reminder template
    EmailTemplate.objects.get_or_create(
        email_type='course_reminder',
        defaults={
            'subject': 'Påmindelse: {{ course_title }} starter om 2 dage',
            'body_html': '''<p>Kære {{ participant_name }},</p>

<p>Dette er en påmindelse om, at du er tilmeldt kurset <strong>{{ course_title }}</strong>, som starter om 2 dage.</p>

<p><strong>Kursusdetaljer:</strong></p>
<ul>
    <li>Dato: {{ course_date }}</li>
    <li>Sted: {{ course_location }}</li>
    <li>Skole: {{ school_name }}</li>
</ul>

<p>Hvis der er vedhæftet kursusmateriale til denne e-mail, bedes du læse det igennem før kurset.</p>

<p>Vi glæder os til at se dig!</p>

<p>Med venlig hilsen,<br>
Basal</p>''',
            'is_active': True,
        }
    )


def remove_default_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('emails', 'EmailTemplate')
    EmailTemplate.objects.filter(
        email_type__in=['signup_confirmation', 'course_reminder']
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_templates, remove_default_templates),
    ]
