# Generated by Django 5.2.9 on 2025-12-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_add_default_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="PDF eller anden fil der vedhæftes alle e-mails af denne type",
                upload_to="email_attachments/",
                verbose_name="Vedhæftet fil",
            ),
        ),
    ]
