# Generated by Django 5.2.9 on 2025-12-17 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0003_add_template_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="attachment",
        ),
    ]
