# Generated by Django 5.2.10 on 2026-02-04 13:00

from django.db import migrations


def create_school_enrollment_template(apps, schema_editor):
    EmailTemplate = apps.get_model("emails", "EmailTemplate")
    EmailTemplate.objects.get_or_create(
        email_type="school_enrollment_confirmation",
        defaults={
            "subject": "Velkommen til Basal - {{ school_name }}",
            "body_html": """<p>Hej {{ contact_name }},</p>

<p>Tak for jeres tilmelding til Basal! {{ school_name }} er nu tilmeldt.</p>

<h3>Jeres skoleside</h3>
<p>I har nu en side hvor I kan se jeres tilmeldinger og pladser:</p>
<p><a href="{{ school_page_url }}">{{ school_page_url }}</a></p>

<h3>Tilmelding til kurser</h3>
<p>I kan tilmelde jer kurser på to måder:</p>

<ol>
    <li><strong>Via direkte link:</strong><br>
        <a href="{{ signup_url }}">{{ signup_url }}</a></li>
    <li><strong>Via kode:</strong><br>
        Gå til {{ site_url }}/signup/course/ og indtast koden: <strong>{{ signup_password }}</strong></li>
</ol>

<p>Med venlig hilsen,<br>Basal</p>""",
            "is_active": True,
        },
    )


def remove_school_enrollment_template(apps, schema_editor):
    EmailTemplate = apps.get_model("emails", "EmailTemplate")
    EmailTemplate.objects.filter(email_type="school_enrollment_confirmation").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0005_update_template_text"),
    ]

    operations = [
        migrations.RunPython(
            create_school_enrollment_template,
            remove_school_enrollment_template,
        ),
    ]
