# Generated by Django 5.2.9 on 2026-02-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0006_add_school_enrollment_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("signup_confirmation", "Tilmeldingsbekræftelse"),
                    ("course_reminder", "Kursuspåmindelse (14 dage før)"),
                    ("school_enrollment_confirmation", "Skoletilmeldingsbekræftelse"),
                ],
                max_length=30,
                verbose_name="E-mail type",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("signup_confirmation", "Tilmeldingsbekræftelse"),
                    ("course_reminder", "Kursuspåmindelse (14 dage før)"),
                    ("school_enrollment_confirmation", "Skoletilmeldingsbekræftelse"),
                ],
                max_length=30,
                unique=True,
                verbose_name="E-mail type",
            ),
        ),
    ]
