# Generated by Django 5.2.9 on 2026-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0008_update_reminder_template_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Beskrivelse af hvornår denne e-mail sendes og til hvem",
                verbose_name="Beskrivelse",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("signup_confirmation", "Tilmeldingsbekræftelse"),
                    ("course_reminder", "Kursuspåmindelse (14 dage før)"),
                    ("school_enrollment_confirmation", "Skoletilmeldingsbekræftelse"),
                    ("coordinator_signup", "Koordinator-tilmeldingsbekræftelse"),
                ],
                max_length=30,
                verbose_name="E-mail type",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("signup_confirmation", "Tilmeldingsbekræftelse"),
                    ("course_reminder", "Kursuspåmindelse (14 dage før)"),
                    ("school_enrollment_confirmation", "Skoletilmeldingsbekræftelse"),
                    ("coordinator_signup", "Koordinator-tilmeldingsbekræftelse"),
                ],
                max_length=30,
                unique=True,
                verbose_name="E-mail type",
            ),
        ),
    ]
