# Generated by Django 5.2.9 on 2026-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0010_seed_coordinator_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("signup_confirmation", "Tilmeldingsbekræftelse"),
                    ("course_reminder", "Kursuspåmindelse (14 dage før)"),
                    ("school_enrollment_confirmation", "Skoletilmeldingsbekræftelse"),
                    ("coordinator_signup", "Koordinator-tilmeldingsbekræftelse"),
                    ("webinar_confirmation", "Webinarbekræftelse"),
                ],
                max_length=30,
                verbose_name="E-mail type",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("signup_confirmation", "Tilmeldingsbekræftelse"),
                    ("course_reminder", "Kursuspåmindelse (14 dage før)"),
                    ("school_enrollment_confirmation", "Skoletilmeldingsbekræftelse"),
                    ("coordinator_signup", "Koordinator-tilmeldingsbekræftelse"),
                    ("webinar_confirmation", "Webinarbekræftelse"),
                ],
                max_length=30,
                unique=True,
                verbose_name="E-mail type",
            ),
        ),
    ]
