# Generated by Django 5.2.9 on 2026-05-06 14:10

from django.db import migrations

WEBINAR_BODY = """
<p>Hej {{ participant_name }},</p>

<p>Tak for din tilmelding til webinaret <strong>{{ webinar_title }}</strong>.</p>

<p><strong>Hvornår:</strong> {{ webinar_date }}<br>
<strong>Varighed:</strong> {{ webinar_duration }} minutter</p>

{% if instructors %}<p><strong>Undervisere:</strong> {{ instructors }}</p>{% endif %}

<p><strong>Mødelink:</strong> <a href="{{ meeting_url }}">{{ meeting_url }}</a></p>

{% if webinar_description %}<hr>{{ webinar_description|safe }}{% endif %}

<p>Vi glæder os til at se dig.</p>
<p>Mvh.<br>Basal</p>
""".strip()


def seed(apps, schema_editor):
    EmailTemplate = apps.get_model("emails", "EmailTemplate")
    EmailTemplate.objects.update_or_create(
        email_type="webinar_confirmation",
        defaults={
            "subject": "Bekræftelse: tilmelding til {{ webinar_title }}",
            "body_html": WEBINAR_BODY,
            "is_active": True,
            "description": "Sendes til deltageren ved tilmelding til et webinar.",
        },
    )


def unseed(apps, schema_editor):
    EmailTemplate = apps.get_model("emails", "EmailTemplate")
    EmailTemplate.objects.filter(email_type="webinar_confirmation").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0011_alter_emaillog_email_type_and_more"),
    ]
    operations = [
        migrations.RunPython(seed, unseed),
    ]
